const teaItems = [
    {
        name: 'Mano',
        price: 2.2,
        category: 'blend',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel, quas.',
        img: 'https://picsum.photos/200',
    },
    {
        name: 'Weno',
        price: 1.89,
        category: 'Aplus',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel, quas.',
        img: 'https://picsum.photos/200',
    },
    {
        name: 'Leno',
        price: 2.0,
        category: 'blend',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel, quas.',
        img: 'https://picsum.photos/200',
    },
    {
        name: 'Bingo',
        price: 2.2,
        category: 'Aplus',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel, quas.',
        img: 'https://picsum.photos/200',
    },
    {
        name: 'Swingo',
        price: 0.35,
        category: 'blendi',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel, quas.',
        img: 'https://picsum.photos/200',
    },
    {
        name: 'Panawi',
        price: 0.99,
        category: 'Aplus',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel, quas.',
        img: 'https://picsum.photos/200',
    },
    {
        name: 'Separ',
        price: 2.99,
        category: 'blend',
        img: 'https://picsum.photos/200',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel, quas.',
    },
    {
        name: 'Anama',
        price: 3.82,
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel, quas.',
        img: 'https://picsum.photos/200',
        category: 'Aplus',
    },
    {
        name: 'Wepur',
        price: 3.6,
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel, quas.',
        category: 'blend',
        img: 'https://picsum.photos/200',
    },
    {
        name: 'Biano',
        price: 2.67,
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel, quas.',
        category: 'Aplus',
        img: 'https://picsum.photos/200',
    },
    {
        name: 'Sebur',
        price: 0.72,
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel, quas.',
        category: 'blend',
        img: 'https://picsum.photos/200',
    },
    {
        name: 'partu',
        price: 2.7,
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel, quas.',
        category: 'Eptem',
        img: 'https://picsum.photos/200',
    },
    {
        name: 'Delis',
        price: 4.2,
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel, quas.',
        category: 'Eptem',
        img: 'https://picsum.photos/200',
    },
    {
        name: 'Buis',
        price: 3.2,
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel, quas.',
        category: 'Eptem',
        img: 'https://picsum.photos/200',
    },
    {
        name: 'Blir',
        price: 1.5,
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel, quas.',
        category: 'blend',
        img: 'https://picsum.photos/200',
    },
    {
        name: 'Wemi',
        price: 0.2,
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel, quas.',
        category: 'Reem',
        img: 'https://picsum.photos/200',
    },
    {
        name: 'Kentis',
        price: 0.8,
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel, quas.',
        category: 'Orange',
        img: 'https://picsum.photos/200',
    },
    {
        name: 'Yer',
        price: 1.2,
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel, quas.',
        category: 'Orange',
        img: 'https://picsum.photos/200',
    },
];
